 events {}

 stream {
     upstream rabbitmq_cluster {
         random;
         server rabbitmq-1:5672;
         server rabbitmq-2:5672;
     }

     server {
         listen 5672;
         proxy_pass rabbitmq_cluster;
     }
 }
